# Data Cleaning

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('ca_takehome_assessment.csv')

In [4]:
df

,ticket_id,CREATED_DAY,CLOSED_DAY,CREATED_TIME,SUPPORT_CHANNEL,user_type,COUNTRY,ISSUE_TYPE_CATEGORY,TICKET_REPLIES,CALL_LENGTH_MIN,CHAT_DURATION_MIN,FULL_RESOLUTION_TIME,SURVEY_SCORE
0,1,1.622680e+12,1.623630e+12,21:48.0,phone,business,us,desktop app,NaN,7.766667,NaN,NaN,NaN
1,2,1.615250e+12,1.615850e+12,34:30.0,email,business,us,payments,1.0,NaN,NaN,93.466667,NaN
2,3,1.617240e+12,1.617580e+12,36:34.0,chat,business,jp,desktop app,1.0,NaN,12.716667,4.766667,5.0
3,4,1.619650e+12,1.620260e+12,18:24.0,chat,business,jp,admin console,2.0,NaN,31.116667,37.700000,4.0
4,5,1.613260e+12,1.613870e+12,52:45.0,email,business,au,sharing,1.0,NaN,NaN,54.050000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,1.619400e+12,1.619740e+12,17:52.0,chat,paid individual,ca,payments,1.0,NaN,12.333333,0.583333,3.0
49996,49997,1.611710e+12,1.612310e+12,29:21.0,chat,paid individual,dk,desktop app,1.0,NaN,19.600000,58.516667,4.0
49997,49998,1.618880e+12,1.619220e+12,41:08.0,chat,paid individual,ca,desktop app,1.0,NaN,34.866667,0.566667,5.0
49998,49999,1.617670e+12,1.618620e+12,15:26.0,email,paid individual,gb,account security,0.0,NaN,NaN,123.683333,NaN
49999,50000,1.619400e+12,1.619740e+12,17:07.0,chat,paid individual,us,sharing,1.0,NaN,24.450000,0.433333,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ticket_id             50000 non-null  int64
 1   CREATED_DAY           50000 non-null  float64
 2   CLOSED_DAY            49969 non-null  float64
 3   CREATED_TIME          50000 non-null  object
 4   SUPPORT_CHANNEL       50000 non-null  object
 5   user_type             49637 non-null  object
 6   COUNTRY               49503 non-null  object
 7   ISSUE_TYPE_CATEGORY   50000 non-null  object
 8   TICKET_REPLIES        49450 non-null  float64
 9   CALL_LENGTH_MIN       4478 non-null   float64
 10  CHAT_DURATION_MIN     27390 non-null  float64
 11  FULL_RESOLUTION_TIME  49247 non-null  float64
 12  SURVEY_SCORE          13613 non-null  float64
dtypes: float64(7), int64(1), object(5)
memory usage: 5.0+ MB

In [6]:
df.isnull().sum()

ticket_id                   0
CREATED_DAY                 0
CLOSED_DAY                 31
CREATED_TIME                0
SUPPORT_CHANNEL             0
user_type                 363
COUNTRY                   497
ISSUE_TYPE_CATEGORY         0
TICKET_REPLIES            550
CALL_LENGTH_MIN         45522
CHAT_DURATION_MIN       22610
FULL_RESOLUTION_TIME      753
SURVEY_SCORE            36387
dtype: int64

In [16]:
grouped_user_type = df.groupby('user_type').size().reset_index(name='ticket_count')

In [17]:
print(grouped_user_type)

         user_type  ticket_count
0         business         19822
1         hs: free          2589
2         hs: paid          2073
3  paid individual         25153

In [24]:
#making all column names uppercase
df.columns = [col.upper() for col in df.columns]

In [25]:
df

,TICKET_ID,CREATED_DAY,CLOSED_DAY,CREATED_TIME,SUPPORT_CHANNEL,USER_TYPE,COUNTRY,ISSUE_TYPE_CATEGORY,TICKET_REPLIES,CALL_LENGTH_MIN,CHAT_DURATION_MIN,FULL_RESOLUTION_TIME,SURVEY_SCORE
0,1,1.622680e+12,1.623630e+12,21:48.0,phone,business,us,desktop app,NaN,7.766667,NaN,NaN,NaN
1,2,1.615250e+12,1.615850e+12,34:30.0,email,business,us,payments,1.0,NaN,NaN,93.466667,NaN
2,3,1.617240e+12,1.617580e+12,36:34.0,chat,business,jp,desktop app,1.0,NaN,12.716667,4.766667,5.0
3,4,1.619650e+12,1.620260e+12,18:24.0,chat,business,jp,admin console,2.0,NaN,31.116667,37.700000,4.0
4,5,1.613260e+12,1.613870e+12,52:45.0,email,business,au,sharing,1.0,NaN,NaN,54.050000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,1.619400e+12,1.619740e+12,17:52.0,chat,paid individual,ca,payments,1.0,NaN,12.333333,0.583333,3.0
49996,49997,1.611710e+12,1.612310e+12,29:21.0,chat,paid individual,dk,desktop app,1.0,NaN,19.600000,58.516667,4.0
49997,49998,1.618880e+12,1.619220e+12,41:08.0,chat,paid individual,ca,desktop app,1.0,NaN,34.866667,0.566667,5.0
49998,49999,1.617670e+12,1.618620e+12,15:26.0,email,paid individual,gb,account security,0.0,NaN,NaN,123.683333,NaN
49999,50000,1.619400e+12,1.619740e+12,17:07.0,chat,paid individual,us,sharing,1.0,NaN,24.450000,0.433333,NaN

In [34]:
#changing to datetime

df['CREATED_DAY'] = pd.to_datetime(df['CREATED_DAY'], unit='ms', errors='coerce')

In [32]:
df['CLOSED_DAY'] = pd.to_datetime(df['CLOSED_DAY'], unit='ms', errors='coerce')

In [35]:
df

,TICKET_ID,CREATED_DAY,CLOSED_DAY,CREATED_TIME,SUPPORT_CHANNEL,USER_TYPE,COUNTRY,ISSUE_TYPE_CATEGORY,TICKET_REPLIES,CALL_LENGTH_MIN,CHAT_DURATION_MIN,FULL_RESOLUTION_TIME,SURVEY_SCORE,created_day
0,1,2021-06-03 00:26:40,2021-06-14 00:20:00,21:48.0,phone,business,us,desktop app,NaN,7.766667,NaN,NaN,NaN,2021-06-03 00:26:40
1,2,2021-03-09 00:33:20,2021-03-15 23:13:20,34:30.0,email,business,us,payments,1.0,NaN,NaN,93.466667,NaN,2021-03-09 00:33:20
2,3,2021-04-01 01:20:00,2021-04-04 23:46:40,36:34.0,chat,business,jp,desktop app,1.0,NaN,12.716667,4.766667,5.0,2021-04-01 01:20:00
3,4,2021-04-28 22:46:40,2021-05-06 00:13:20,18:24.0,chat,business,jp,admin console,2.0,NaN,31.116667,37.700000,4.0,2021-04-28 22:46:40
4,5,2021-02-13 23:46:40,2021-02-21 01:13:20,52:45.0,email,business,au,sharing,1.0,NaN,NaN,54.050000,NaN,2021-02-13 23:46:40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,2021-04-26 01:20:00,2021-04-29 23:46:40,17:52.0,chat,paid individual,ca,payments,1.0,NaN,12.333333,0.583333,3.0,2021-04-26 01:20:00
49996,49997,2021-01-27 01:13:20,2021-02-02 23:53:20,29:21.0,chat,paid individual,dk,desktop app,1.0,NaN,19.600000,58.516667,4.0,2021-01-27 01:13:20
49997,49998,2021-04-20 00:53:20,2021-04-23 23:20:00,41:08.0,chat,paid individual,ca,desktop app,1.0,NaN,34.866667,0.566667,5.0,2021-04-20 00:53:20
49998,49999,2021-04-06 00:46:40,2021-04-17 00:40:00,15:26.0,email,paid individual,gb,account security,0.0,NaN,NaN,123.683333,NaN,2021-04-06 00:46:40
49999,50000,2021-04-26 01:20:00,2021-04-29 23:46:40,17:07.0,chat,paid individual,us,sharing,1.0,NaN,24.450000,0.433333,NaN,2021-04-26 01:20:00

In [37]:
#dropping rows with important info missing
df.dropna(subset=['USER_TYPE', 'COUNTRY', 'ISSUE_TYPE_CATEGORY'], inplace=True)

In [38]:
df

,TICKET_ID,CREATED_DAY,CLOSED_DAY,CREATED_TIME,SUPPORT_CHANNEL,USER_TYPE,COUNTRY,ISSUE_TYPE_CATEGORY,TICKET_REPLIES,CALL_LENGTH_MIN,CHAT_DURATION_MIN,FULL_RESOLUTION_TIME,SURVEY_SCORE,created_day
0,1,2021-06-03 00:26:40,2021-06-14 00:20:00,21:48.0,phone,business,us,desktop app,NaN,7.766667,NaN,NaN,NaN,2021-06-03 00:26:40
1,2,2021-03-09 00:33:20,2021-03-15 23:13:20,34:30.0,email,business,us,payments,1.0,NaN,NaN,93.466667,NaN,2021-03-09 00:33:20
2,3,2021-04-01 01:20:00,2021-04-04 23:46:40,36:34.0,chat,business,jp,desktop app,1.0,NaN,12.716667,4.766667,5.0,2021-04-01 01:20:00
3,4,2021-04-28 22:46:40,2021-05-06 00:13:20,18:24.0,chat,business,jp,admin console,2.0,NaN,31.116667,37.700000,4.0,2021-04-28 22:46:40
4,5,2021-02-13 23:46:40,2021-02-21 01:13:20,52:45.0,email,business,au,sharing,1.0,NaN,NaN,54.050000,NaN,2021-02-13 23:46:40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,2021-04-26 01:20:00,2021-04-29 23:46:40,17:52.0,chat,paid individual,ca,payments,1.0,NaN,12.333333,0.583333,3.0,2021-04-26 01:20:00
49996,49997,2021-01-27 01:13:20,2021-02-02 23:53:20,29:21.0,chat,paid individual,dk,desktop app,1.0,NaN,19.600000,58.516667,4.0,2021-01-27 01:13:20
49997,49998,2021-04-20 00:53:20,2021-04-23 23:20:00,41:08.0,chat,paid individual,ca,desktop app,1.0,NaN,34.866667,0.566667,5.0,2021-04-20 00:53:20
49998,49999,2021-04-06 00:46:40,2021-04-17 00:40:00,15:26.0,email,paid individual,gb,account security,0.0,NaN,NaN,123.683333,NaN,2021-04-06 00:46:40
49999,50000,2021-04-26 01:20:00,2021-04-29 23:46:40,17:07.0,chat,paid individual,us,sharing,1.0,NaN,24.450000,0.433333,NaN,2021-04-26 01:20:00

In [39]:
df = df[
    (df['CALL_LENGTH_MIN'].isnull()) | ((df['CALL_LENGTH_MIN'] >= 0) & (df['CALL_LENGTH_MIN'] < 1440))
]
df = df[
    (df['CHAT_DURATION_MIN'].isnull()) | ((df['CHAT_DURATION_MIN'] >= 0) & (df['CHAT_DURATION_MIN'] < 1440))
]
df = df[
    (df['FULL_RESOLUTION_TIME'].isnull()) | ((df['FULL_RESOLUTION_TIME'] >= 0) & (df['FULL_RESOLUTION_TIME'] < 1440))
]

In [40]:
df

,TICKET_ID,CREATED_DAY,CLOSED_DAY,CREATED_TIME,SUPPORT_CHANNEL,USER_TYPE,COUNTRY,ISSUE_TYPE_CATEGORY,TICKET_REPLIES,CALL_LENGTH_MIN,CHAT_DURATION_MIN,FULL_RESOLUTION_TIME,SURVEY_SCORE,created_day
0,1,2021-06-03 00:26:40,2021-06-14 00:20:00,21:48.0,phone,business,us,desktop app,NaN,7.766667,NaN,NaN,NaN,2021-06-03 00:26:40
1,2,2021-03-09 00:33:20,2021-03-15 23:13:20,34:30.0,email,business,us,payments,1.0,NaN,NaN,93.466667,NaN,2021-03-09 00:33:20
2,3,2021-04-01 01:20:00,2021-04-04 23:46:40,36:34.0,chat,business,jp,desktop app,1.0,NaN,12.716667,4.766667,5.0,2021-04-01 01:20:00
3,4,2021-04-28 22:46:40,2021-05-06 00:13:20,18:24.0,chat,business,jp,admin console,2.0,NaN,31.116667,37.700000,4.0,2021-04-28 22:46:40
4,5,2021-02-13 23:46:40,2021-02-21 01:13:20,52:45.0,email,business,au,sharing,1.0,NaN,NaN,54.050000,NaN,2021-02-13 23:46:40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,2021-04-26 01:20:00,2021-04-29 23:46:40,17:52.0,chat,paid individual,ca,payments,1.0,NaN,12.333333,0.583333,3.0,2021-04-26 01:20:00
49996,49997,2021-01-27 01:13:20,2021-02-02 23:53:20,29:21.0,chat,paid individual,dk,desktop app,1.0,NaN,19.600000,58.516667,4.0,2021-01-27 01:13:20
49997,49998,2021-04-20 00:53:20,2021-04-23 23:20:00,41:08.0,chat,paid individual,ca,desktop app,1.0,NaN,34.866667,0.566667,5.0,2021-04-20 00:53:20
49998,49999,2021-04-06 00:46:40,2021-04-17 00:40:00,15:26.0,email,paid individual,gb,account security,0.0,NaN,NaN,123.683333,NaN,2021-04-06 00:46:40
49999,50000,2021-04-26 01:20:00,2021-04-29 23:46:40,17:07.0,chat,paid individual,us,sharing,1.0,NaN,24.450000,0.433333,NaN,2021-04-26 01:20:00

In [42]:
#exporting clean data into csv file
df.to_csv('cleaned_df.csv', index=False)